version: '3'

services:
    database:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=main
            - MYSQL_USER=spring
            - MYSQL_PASSWORD=spring
        ports:
            - '3306'
    configserver:
        build: configserver/
        environment:
            ENCRYPT_KEY: 'mysecret'
        ports:
            - '8888:8888'
    zuulserver:
        build: zuulserver/
        ports:
            - '5555:5555'
        depends_on:
            - configserver
            - eurekaserver
    authentication:
        build: authentication/
        restart: on-failure
        depends_on:
            - configserver
    eurekaserver:
        build: eurekaserver/
        depends_on:
            - configserver
        ports:
            - '8761:8761'
    licenses:
        build: licenses/
        restart: on-failure
        depends_on:
            - configserver
            - database
            - eurekaserver
    organizations:
        build: organizations
        restart: on-failure
        depends_on:
            - configserver
            - database
            - eurekaserver
    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.1
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-server:5.4.1
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    control-center:
        image: confluentinc/cp-enterprise-control-center:5.4.1
        depends_on:
            - zookeeper
            - kafka
        ports:
            - "9021:9021"
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
            CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#            CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
            CONFLUENT_METRICS_TOPIC_REPLICATION: 1
            PORT: 9021
