zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    organizations: /organizations/**
    licenses: /licenses/**
    authentication: /authentication/**
  debug:
    request: true
  sensitiveHeaders: Cookie,Set-Cookie