tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "MYSQL"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.mysql.jdbc.Driver"
spring.database.url: "jdbc:mysql://localhost/tmx-config"
spring.database.username: "root"
spring.database.password: "root"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"