eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        inboundOrganizationChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: zookeeper
          brokers: kafka:29092

security:
  oauth2:
    resource:
      user-info-uri: http://authentication:8082/user